from turtle import title
from turtle import Turtle
from time import sleep
title("Train drawing in python by Jude M. (With help from my brother Ethan)")
kappa = Turtle()
def plow():
    kappa.hideturtle()
    kappa.color("red")
    kappa.pencolor("black")
    kappa.fillcolor("red")
    kappa.penup()
    kappa.goto(-180, 40)
    kappa.pendown()
    kappa.showturtle()
    kappa.begin_fill()
    kappa.right(90)
    kappa.hideturtle()
    kappa.goto(-180, -120)
    kappa.showturtle()
    kappa.right(90)
    kappa.forward(60)
    kappa.right(90)
    kappa.forward(100)
    kappa.right(40)
    kappa.forward(90)
    kappa.end_fill()
def front_body():
    kappa.color("yellow")
    kappa.pencolor("black")
    kappa.fillcolor("yellow")
    kappa.begin_fill()
    kappa.right(50)
    kappa.forward(220)
    kappa.right(90)
    kappa.forward(180)
    kappa.right(90)
    kappa.forward(220)
    kappa.end_fill()
    kappa.penup()
def wheels():
    kappa.color("yellow")
    kappa.pencolor("black")
    kappa.fillcolor("yellow")
    kappa.hideturtle()
    kappa.goto(20, -170)
    kappa.showturtle()
    kappa.pendown()
    kappa.begin_fill()
    kappa.circle(50)
    kappa.end_fill()
    kappa.penup()
    wheel_circle()
    kappa.penup()
    kappa.pencolor("black")
    kappa.color("blue")
    kappa.fillcolor("blue")
    kappa.hideturtle()
    kappa.goto(-100, -160)
    kappa.showturtle()
    kappa.pendown()
    kappa.begin_fill()
    kappa.circle(40)
    kappa.end_fill()
    kappa.penup()
    kappa.right(90)
    kappa.forward(80)
    kappa.left(270)
    kappa.forward(5)
    kappa.pendown()
    kappa.begin_fill()
    kappa.circle(40)
    kappa.end_fill()
    kappa.penup()
def wheels_connectors():
    kappa.hideturtle()
    kappa.goto(70, -165)
    kappa.showturtle()
    kappa.color("yellow")
    kappa.pencolor("black")
    kappa.fillcolor("yellow")
    kappa.pendown()
    kappa.begin_fill()
    for i in range(2):
        kappa.left(90)
        kappa.forward(120)
        kappa.left(90)
        kappa.forward(30)
    kappa.end_fill()
    kappa.penup()
    kappa.hideturtle()
    kappa.goto(-50, -160)
    kappa.showturtle()
    kappa.left(90)
    kappa.pendown()
    kappa.begin_fill()
    for i in range(2):
        kappa.forward(165)
        kappa.left(90)
        kappa.forward(20)
        kappa.left(90)
    kappa.end_fill()
    kappa.penup()
    kappa.color("red")
    kappa.pencolor("black")
    kappa.fillcolor("red")
    kappa.hideturtle()
    kappa.goto(-30, -160)
    kappa.showturtle()
    kappa.pendown()
    kappa.begin_fill()
    for i in range(4):
        kappa.forward(40)
        kappa.left(90)
    kappa.end_fill()

def back():
    kappa.color("blue")
    kappa.pencolor("black")
    kappa.fillcolor("blue")
    kappa.hideturtle()
    kappa.goto(40, 180)
    kappa.showturtle()
    kappa.pendown()
    kappa.begin_fill()
    kappa.left(90)
    for i in range(2):
        kappa.forward(320)
        kappa.left(90)
        kappa.forward(60)
        kappa.left(90)
    kappa.end_fill()
    kappa.penup()
def back_square():
    kappa.hideturtle()
    kappa.goto(50, 160)
    kappa.showturtle()
    kappa.color("yellow")
    kappa.fillcolor("yellow")
    kappa.pencolor("black")
    kappa.begin_fill()
    kappa.pendown()
    for i in range(4):
        kappa.forward(40)
        kappa.left(90)
    kappa.end_fill()
    kappa.penup()
def wheel_circle():
    kappa.color("blue")
    kappa.fillcolor("blue")
    kappa.hideturtle()
    kappa.goto(40, -175)
    kappa.showturtle()
    kappa.pendown()
    kappa.begin_fill()
    kappa.circle(30)
    kappa.end_fill()
    kappa.penup()
def whistle():
    kappa.penup()
    kappa.color("blue")
    kappa.pencolor("black")
    kappa.fillcolor("blue")
    kappa.hideturtle()
    kappa.goto(-100, 50)
    kappa.showturtle()
    kappa.right(90)
    kappa.pendown()
    kappa.begin_fill()
    for i in range(2):
        kappa.forward(100)
        kappa.right(90)
        kappa.forward(40)
        kappa.right(90)
    kappa.end_fill()
    kappa.penup()
    kappa.forward(100)
    kappa.pendown()
    kappa.color("red")
    kappa.fillcolor("red")
    kappa.begin_fill()
    kappa.forward(20)
    kappa.left(30)
    kappa.forward(100)
    kappa.right(120)
    kappa.forward(120)
    kappa.right(110)
    kappa.forward(80)
    kappa.left(10)
    kappa.forward(33)
    kappa.end_fill()
    kappa.penup()
    kappa.goto(-100, 50)
    kappa.right(170)
    kappa.forward(120)
    kappa.right(90)
    kappa.color("yellow")
    kappa.fillcolor("yellow")
    kappa.pendown()
    kappa.begin_fill()
    kappa.forward(39)
    kappa.right(90)
    kappa.forward(20)
    kappa.right(90)
    kappa.forward(39)
    kappa.right(90)
    kappa.forward(20)
    kappa.end_fill()

# You can change the execution order of the functions but the recommended order is:
# plow, front_body, back, back_square, wheels, wheels_connectors, whistle
plow()
front_body()
back()
back_square()
wheels()
wheels_connectors()
whistle()
print("Credits:")
sleep(1)
print("Made by Jude M.")
sleep(1)
print("Special thanks to my brother Ethan for giving me ideas")
sleep(3)
print("FIN")