# A calculator in python with all the operations except or, and the wait command[time.sleep( )]
from time import sleep
from sys import exit
from turtle import Turtle
print("Starting up...")
sleep(2)
print("Hello, I am your personal asistant Pycalc")
sleep(1)
print("I can do everything a calculator can do!!!")
sleep(1)
name = input("What is your name? > ")
if name == "butt jim":
    print("Get out of here,", name)
    sleep(10)
    print("You won't?")
    sleep(8)
    print("Auuuuuuuuuuuuuuuuuuuuuggggggggggggggggggggggghhhhhhhhhhhhhhhhhhhhhhhhhhhh!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    sleep(5)
    print("I can't take it anymore!!!!!!!!!!!!!!!!")
    sleep(10)
    print("ShUtTiNg DoWn?.!")
    sleep(10)
    exit(["ERR_BUTT_JIM"])
elif name == "Mr. Ritchie":
    print("Hey,", name)
    sleep(1)
    print("Hope you like my script!!!!")
elif name == "mr. ricthie":
    print("Hey,", name)
    sleep(1)
    print("Hope you like my script!!!!")
elif name == "Ms. Cote":
    print("Hey, ", name)
    sleep(1)
    print("Hope you like my script!!!!")
elif name == "ms. cote":
    print("Hey,", name)
    sleep(1)
    print("Hope you like my script!!!!")
elif name == "ms cote":
    print("Hey,", name)
    sleep(1)
    print("Hope you like my script!!!!")
elif name == "mr ritchie":
    print("Hey,", name)
    sleep(1)
    print("Hope you like my script!!!!")
elif name == "Mr Ritchie":
    print("Hey,", name)
    time.sleep(1)
    print("Hope you like my script!!!!")
elif name == "Ms Cote":
    print("Hey,", name)
    sleep(1)
    print("Hope you like my script!!!!")
elif name == "":
    print("Sorry, but you must enter a name")
    sleep(1)
    print("Shutting down...")
    sleep(2)
    exit(["ERR_USER_NAME_MISSING"])
else:
    print("Hello,", name)


sleep(1)
num1 = float(input("What is the first number you would like to put in? > "))
num2 = float(input("What is the second number you would like to put in?  > "))
num1_float = float(num1)
num2_float = float(num2)
SUMd = num1_float / num2_float
SUMm = num1_float * num2_float
SUMs = num1_float - num2_float
SUMa = num1_float + num2_float
operation = input("Would you like to (D)ivide, (M)ultiply, (S)ubtract, or (A)dd? > ")
if operation == "D":
    print("Time to divide!!!")
    sleep(0.5)
    print("Dividing...")
    sleep(1)
    print("It appears that,", num1, "divided by", num2, "is equal to,", SUMd)
elif operation == "d":
    print("Time to divide!!!")
    sleep(0.5)
    print("Dividing...")
    time.sleep(1)
    print("It appears that,", num1, "divided by", num2, "is equal to,", SUMd)
elif operation == "M":
    print("Time to multiply")
    sleep(0.5)
    print("Multiplying...")
    sleep(1)
    print("It appears that,", num1, "multiplied by", num2, "is equal to,", SUMm)
elif operation == "m":
    print("Time to multiply")
    sleep(0.5)
    print("Multiplying...")
    sleep(1)
    print("It appears that,", num1, "multiplied by", num2, "is equal to,", SUMm)
elif operation == "S":
    print("Time to subtract")
    sleep(0.5)
    print("Subtracting...")
    sleep(1)
    print("It appears that,", num1, "minus", num2, "is equal to,", SUMs)
elif operation == "s":
    print("Time to subtract")
    sleep(0.5)
    print("Subtracting...")
    sleep(1)
    print("It appears that,", num1, "minus", num2, "is equal to,", SUMs)
elif operation == "A":
    print("Time to add")
    sleep(0.5)
    print("Adding...")
    sleep(1)
    print("It appears that,", num1, "plus", num2, "is equal to,", SUMa)
elif operation == "a":
    print("Time to add")
    sleep(0.5)
    print("Adding...")
    sleep(1)
    print("It appears that,", num1, "plus", num2, "is equal to,", SUMa)
elif operation == "Divide":
    print("Time to divide!!!")
    sleep(0.5)
    print("Dividing...")
    sleep(1)
    print("It appears that,", num1, "divided by", num2, "is equal to,", SUMd)
elif operation == "divide":
    print("Time to divide!!!")
    sleep(0.5)
    print("Dividing...")
    sleep(1)
    print("It appears that,", num1, "divided by", num2, "is equal to,", SUMd)
elif operation == "multiply":
    print("Time to multiply")
    sleep(0.5)
    print("Multiplying...")
    sleep(1)
    print("It appears that,", num1, "multiplied by", num2, "is equal to,", SUMm)
elif operation == "Multiply":
    print("Time to multiply")
    sleep(0.5)
    print("Multiplying...")
    sleep(1)
    print("It appears that,", num1, "multiplied by", num2, "is equal to,", SUMm)
elif operation == "Subtract":
    print("Time to subtract")
    sleep(0.5)
    print("Subtracting...")
    sleep(1)
    print("It appears that,", num1, "minus", num2, "is equal to,", SUMs)
elif operation == "subtract":
    print("Time to subtract")
    sleep(0.5)
    print("Subtracting...")
    sleep(1)
    print("It appears that,", num1, "minus", num2, "is equal to,", SUMs)
elif operation == "Add":
    print("Time to add")
    sleep(0.5)
    print("Adding...")
    sleep(1)
    print("It appears that,", num1, "plus", num2, "is equal to,", SUMa)
elif operation == "add":
    print("Time to add")
    sleep(0.5)
    print("Adding...")
    sleep(1)
    print("It appears that,", num1, "plus", num2, "is equal to,", SUMa)
elif operation == "/":
    print("Time to divide!!!")
    sleep(0.5)
    print("Dividing...")
    sleep(1)
    print("It appears that,", num1, "divided by", num2, "is equal to,", SUMd)
elif operation == "*":
    print("Time to multiply")
    sleep(0.5)
    print("Multiplying...")
    sleep(1)
    print("It appears that,", num1, "multiplied by", num2, "is equal to,", SUMm)
elif operation == "x":
    print("Time to multiply")
    sleep(0.5)
    print("Multiplying...")
    sleep(1)
    print("It appears that,", num1, "multiplied by", num2, "is equal to,", SUMm)
elif operation == "-":
    print("Time to subtract")
    sleep(0.5)
    print("Subtracting...")
    sleep(1)
    print("It appears that,", num1, "minus", num2, "is equal to,", SUMs)
elif operation == "+":
    print("Time to add")
    sleep(0.5)
    print("Adding...")
    sleep(1)
    print("It appears that,", num1, "plus", num2, "is equal to,", SUMa)
else:
    print("This operation is invalid: accepted inputs are: D, d, divide, Divide, /, M, m, multiply, Multiply, *, x, S, s, Subtract, subtract, -, A, a, Add, add, and +")
    reading = input("Press enter or return once you are done reading this statement >")
    sleep(2)
    print("Shutting down...")
    sleep(2)
    exit(["ERR_OPERATION_MISSING"])
sleep(2)
print("Thank you for using me,", name)
sleep(1)
print("Until next time,")
sleep(0.5)
print("Shutting down...")
sleep(2)
input("Powered off")
sleep(10)
print("It's off, so just close the window")
sleep(20)
print("Please just close the window")
sleep(5)
print("Just close it already!!!!!!!!!!!!!!")
input("OFF")
sleep(90)
kappa = Turtle()
kappa.forward(500)
kappa.backward(500)
kappa.left(90)
kappa.forward(500)
kappa.backward(500)
kappa.left(90)
kappa.forward(500)
kappa.backward(500)
kappa.left(90)
kappa.forward(500)
kappa.backward(500)
print("90 seconds have passed")
sleep(0.5)
print("Contacting developper...")
sleep(2)
print("Done")
sleep(1)
print("Oh, who is there?")
sleep(1)
print("Oh, it's someone named,", name)
sleep(1)
print("Well, hello,", name)
sleep(1)
print("I don't know why you would want to wait 3 minutes, but, thank you for doing so,", name)
sleep(1)
print("I just want to thank you for taking the time to see my python script")
sleep(1)
print("You are probably one of only a few who have seen this script, so I bundled a secret message")
sleep(1)
print("You just have to type in the secret key")
sleep(1)
print("Good luck,", name)
sleep(1)
key = input("What is the key? > ")
if key == "spacedude609":
    print("If you want to see a secret message go to this MediaFire link, http://www.mediafire.com/file/s8outsf9vilio1d/Message+from+the+dev.py/file ")
    print("You can also go to a link in my personal OneDrive, https://1drv.ms/u/s!ArudfbOpJsF_x0_SNPBQRdPKEAJa ")
    print("Or, my school OneDrive, https://swlsb-my.sharepoint.com/:u:/g/personal/0398313_swlauriersb_qc_ca/EaA0HQdw_v5EnjgptCEnaGcBWyrqWb-bQmIX3Q6xv_fQVQ?e=aNNNL8")
    print("If you are prompted, the password is: Python")
    print("It's Ctrl+Shift+C to copy as Ctrl+C terminates the program")
elif key == "butt jim":
    print("Just stop")
    sleep(1)
    exit(["ERR_BUTT_JIM"])
else:
    print("Wrong")
    sleep(1)
    print("try again!!!!!!")
    exit(["ERR_WRONG_KEY"])
print("The program will not stop automatically please press Ctrl+C or close the windows to stop it")
sleep(3000)