import time
print("90 seconds have passed, contacting developer...")
time.sleep(2)
print("Done")
time.sleep(1)
print("Hello?")
time.sleep(1)
print("Oh, hi there,", name)
time.sleep(1)
print("I'm Jude Middleton, the creator of this program.")
time.sleep(1)
print("Or, at least the Python version of myself")
time.sleep(1)
print("I just wanna say, thank you for being there to try out my python calculator,", name)
time.sleep(1)
print("Well, what else is there to talk about... I mean, you have just waited 90 seconds for this.")
print("Well, I guess I'll be on my way, you know where to contact me if you want to talk in person.")
print("Bye")
time.sleep(3)