from turtle import Turtle
from time import sleep
kappa = Turtle()
kappa.pencolor("gold")
kappa.color("gold")
kappa.fillcolor("gold")
kappa.begin_fill()
for i in range(4):
    kappa.forward(200)
    kappa.left(90)
kappa.end_fill()
kappa.penup()
kappa.hideturtle()
kappa.goto(-300, 0)
kappa.pendown()
kappa.showturtle()
kappa.pencolor("lime")
kappa.color("lime")
kappa.fillcolor("lime")
kappa.begin_fill()
for i in range(2):
    kappa.forward(200)
    kappa.right(90)
    kappa.forward(70)
    kappa.right(90)
kappa.end_fill()
kappa.penup()
kappa.hideturtle()
kappa.goto(300, 0)
kappa.pendown()
kappa.showturtle()
kappa.pencolor("blue")
kappa.color("blue")
kappa.fillcolor("blue")
kappa.begin_fill()
for i in range(3):
    kappa.forward(200)
    kappa.right(120)
kappa.end_fill()
kappa.hideturtle()
print("It is done!!!!!!!!!!!!!!!")
sleep(1)
print("I drew a gold square...")
sleep(1)
print("A green rectangle...")
sleep(1)
print("and a blue triangle!!!!!!!!!!!!")
sleep(30)