from turtle import Turtle
Kappa = Turtle()
Kappa.forward(10)
Kappa.right(90)
Kappa.forward(10)
Kappa.right(90)
Kappa.forward(10)
Kappa.right(90)
Kappa.forward(10)
Kappa.hideturtle()
Kappa.penup()
Kappa.goto(70, 70)
Kappa.showturtle()
Kappa.pendown()
Kappa.forward(30)
Kappa.right(90)
Kappa.forward(30)
Kappa.right(90)
Kappa.forward(30)
Kappa.right(90)
Kappa.forward(30)
Kappa.penup()
Kappa.hideturtle()
Kappa.goto(100, -50)
Kappa.showturtle()
Kappa.pendown()
Kappa.forward(50)
Kappa.right(90)
Kappa.forward(50)
Kappa.right(90)
Kappa.forward(50)
Kappa.right(90)
Kappa.forward(50)
Kappa.penup()
Kappa.hideturtle()
Kappa.goto(0, 0)
del Turtle